import React from 'react';
import PageHeader from '@/components/ui/PageHeader';

export default function Usage() {
  return (
    <div>
      <PageHeader 
        title="Usage Metering" 
        description="Monitor your platform usage against your current plan limits." 
      />
      
      <div className="max-w-3xl space-y-8">
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6">
          <div className="flex justify-between items-end mb-2">
            <div>
              <h3 className="text-lg font-semibold text-slate-900">AI Messages</h3>
              <p className="text-sm text-slate-500">Text messages generated by Chidi.</p>
            </div>
            <div className="text-right">
              <span className="text-2xl font-bold text-slate-900">7,200</span>
              <span className="text-sm text-slate-500"> / 10,000</span>
            </div>
          </div>
          <div className="w-full bg-slate-100 rounded-full h-3 mb-2 overflow-hidden">
            <div className="bg-indigo-600 h-3 rounded-full" style={{ width: '72%' }}></div>
          </div>
          <p className="text-xs text-slate-500 text-right">Resets in 12 days</p>
        </div>
        
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6">
          <div className="flex justify-between items-end mb-2">
            <div>
              <h3 className="text-lg font-semibold text-slate-900">Voice Interface</h3>
              <p className="text-sm text-slate-500">Minutes of STT/TTS generated.</p>
            </div>
            <div className="text-right">
              <span className="text-2xl font-bold text-slate-900">250</span>
              <span className="text-sm text-slate-500"> / 1,000 min</span>
            </div>
          </div>
          <div className="w-full bg-slate-100 rounded-full h-3 mb-2 overflow-hidden">
            <div className="bg-emerald-500 h-3 rounded-full" style={{ width: '25%' }}></div>
          </div>
          <p className="text-xs text-slate-500 text-right">Resets in 12 days</p>
        </div>
      </div>
    </div>
  );
}